In [47]:
import numpy as np
import copy
import pandas as pd

In [6]:
term1 = 'Believe'
term2 = 'beleive'
term3 = 'bargain'
term4 = 'Elephant'

In [7]:
def vectorize_terms(terms):
    terms = [term.lower() for term in terms]
    terms = [np.array(list(term)) for term in terms]
    terms = [np.array([ord(char) for char in term])for term in terms]
    
    return terms


In [8]:
terms = [term1, term2, term3, term4]
termsVec = vectorize_terms(terms)

In [9]:
termsVec

[array([ 98, 101, 108, 105, 101, 118, 101]),
 array([ 98, 101, 108, 101, 105, 118, 101]),
 array([ 98,  97, 114, 103,  97, 105, 110]),
 array([101, 108, 101, 112, 104,  97, 110, 116])]

# Hamming Distance

In [10]:
termsVec

[array([ 98, 101, 108, 105, 101, 118, 101]),
 array([ 98, 101, 108, 101, 105, 118, 101]),
 array([ 98,  97, 114, 103,  97, 105, 110]),
 array([101, 108, 101, 112, 104,  97, 110, 116])]

In [11]:
def HammingDistance(term1, term2, norm=False):
    
    if term1.shape != term2.shape:
        return False
    
    return (term1!=term2).sum() if not norm else (term1 != term2).mean() 
        

In [48]:
HammingDistance(termsVec[0], termsVec[1], norm=False)

2

# Manhattan Distance

In [13]:
def ManhattanDistance(term1, term2, norm=False):
    
    if len(term1) != len(term2):
        return False
    
    return (abs(term1-term2)).sum() if not norm else (abs(term1-term2)).mean()

In [50]:
ManhattanDistance(termsVec[0], termsVec[1], norm=False)

8

# Euclidean Distance

In [15]:
def euclideanDistance(term1, term2):
    if len(term1) != len(term2):
        return False
    return np.sqrt(np.sum(np.square(term1-term2)))

In [51]:
euclideanDistance(termsVec[0], termsVec[1])

5.656854249492381

# Edit Distance

In [17]:
def editDistace(term1, term2):
    
    term1 = term1.lower()
    term2 = term2.lower()
    
    if term1 == term2: return 0
    if len(term1) == 0: return len(term1)
    if len(term2) == 0: return len(term2)
    
    editDistance = []
    
    length = len(term1)
    if len(term1) < len(term2):
        length = len(term2)
    
    dist1 = [0]*(length+1)
    dist2 = [0]*(length+1)
    
    for i in range(len(dist1)):
        dist1[i] = i
    
    for i in range(len(term1)):
        dist2[0] = i + 1
        
        for j in range(len(term2)):
            cost = 0 if term1[i] == term2[j] else 1
            dist2[j+1] = min(dist2[j]+1, dist1[j+1]+1, dist1[j]+cost)
            
        for j in range(len(dist1)):
            dist1[j] = dist2[j]
            
        editDistance.append(copy.copy(dist2))
    distance = dist2[length]
    editMatrix = np.array(editDistance).T
    editMatrix = editMatrix[1:, ]
    editMatrix = pd.DataFrame(data = editMatrix, index = list(term2), columns = list(term1))
    return editMatrix, distance

In [52]:
editMatrix, distance = editDistace(terms[0], terms[3])

In [53]:
editMatrix

b  e  l  i  e  v  e
e  1  1  2  3  4  5  6
l  2  2  1  2  3  4  5
e  3  2  2  2  2  3  4
p  4  3  3  3  3  3  4
h  5  4  4  4  4  4  4
a  6  5  5  5  5  5  5
n  7  6  6  6  6  6  6
t  8  7  7  7  7  7  7

# Cosine Similarity

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances


In [63]:
Sentence1 = "AI is our friend and it has been friendly"
Sentence2 = "AI is our friend and it has been friendly"

Sents = [Sentence1, Sentence2]
countVec = CountVectorizer(Sents).fit(Sents)

In [56]:
countArray = countVec.transform(Sents).toarray()

In [57]:
countArray

array([[1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0]])

In [58]:
cosine_similarity(countArray)

array([[1.        , 0.50395263],
       [0.50395263, 1.        ]])

In [60]:
def jaccardSimilarity(Sentence1, Sentence2):
    a = set(Sentence1.split())
    b = set(Sentence2.split())
    c = a.intersection(b)
    Similarity = float(len(c))/(len(a)+len(b)-len(c))
    return Similarity

In [64]:
Similarity = jaccardSimilarity(Sentence1, Sentence2)

In [65]:
Similarity

1.0